import { ConnectionTest } from "./ConnectionTest";
import { useEffect, useState } from 'react';
import type { LoaConfig } from './App';
import {readNotebook,saveNotebook,download,validate} from './notebookStore';
export function SettingsPanel({config,onSave,onClose}:{config:LoaConfig;onSave:(value:LoaConfig)=>void;onClose:()=>void}){
 const [draft,setDraft]=useState(config),[section,setSection]=useState('General'),[status,setStatus]=useState('');
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose()};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[onClose]);
 function field(key:keyof LoaConfig,label:string,secret=false){return <label className="settingsField">{label}<input type={secret?'password':'text'} autoComplete="off" value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>}
 return <div className="notebookBackdrop" onClick={e=>{if(e.target===e.currentTarget)onClose()}}><section className="notebook settingsPanel" role="dialog" aria-modal="true" aria-label="Settings"><header><h2>Settings</h2><button className="notebookClose" onClick={onClose} aria-label="Close settings">×</button></header><nav>{['General','Connections','Memory & journal','Data'].map(name=><button key={name} aria-pressed={section===name} onClick={()=>setSection(name)}>{name}</button>)}</nav>
 {section==='General'&&<div>{field('userName','Your name')}{field('loaName','Loa name')}<label className="settingsField">Personal instructions<textarea className="personalInstructions" rows={6} maxLength={6000} value={draft.personalInstructions || ''} placeholder="How would you like Loa to talk with you? For example: Keep chatting naturally while I play. Don't tell me to focus on the game unless I ask." onChange={e=>setDraft({...draft,personalInstructions:e.target.value})}/></label><p className="notebookIntro">Applies to voice and chat. Saved in this browser separately from memories. Save changes, then Restart Loa to apply to your current session.</p><label className="settingsField">Speak first while watching<select value={draft.proactiveMode || 'occasional'} onChange={e=>setDraft({...draft,proactiveMode:e.target.value as LoaConfig['proactiveMode']})}><option value="off">Off</option><option value="occasional">Occasionally</option><option value="active">More often</option></select></label><p className="notebookIntro">Comments on screen changes during Live. Additional responses may use API credits.</p><label className="settingsField">Default view<select value={draft.defaultLiveSource} onChange={e=>setDraft({...draft,defaultLiveSource:e.target.value as LoaConfig['defaultLiveSource']})}><option value="ask">Choose when sharing</option><option value="screen">Screen</option><option value="obs">OBS camera</option></select></label></div>}
 {section==='Connections'&&<div>{field('geminiApiKey','Gemini API key',true)}<ConnectionTest apiKey={draft.geminiApiKey} voice={draft.geminiVoice} /><label className="settingsField">Voice<select value={draft.geminiVoice} onChange={e=>setDraft({...draft,geminiVoice:e.target.value as LoaConfig['geminiVoice']})}>{['Puck','Charon','Kore','Fenrir','Aoede','Leda','Orus','Zephyr'].map(v=><option key={v}>{v}</option>)}</select></label>{field('hermesUrl','Hermes URL')}{field('hermesApiKey','Hermes API key',true)}<p className="notebookIntro">Reconnect Live after saving connection changes. Keys are stored in this browser.</p></div>}
 {section==='Memory & journal'&&<div className="settingsFacts"><h3>Automatic memories</h3><p>Loa organizes important conversations into events, meaning, feelings, and next context using Gemini 2.5 Flash in the background. This uses your Gemini key and additional API credits. It can update existing memories; unknown details stay empty. You can review, edit, or delete them below the conversation.</p><h3>Daily journal · 11:50 PM</h3><p>Written once per day using this device’s local time zone. Keep Loa open and Live connected at 11:50 PM. If you reconnect before midnight, Loa can still write that day’s entry.</p><p>This browser app cannot write while closed or disconnected. Journal writing currently uses Live and may also be spoken aloud.</p></div>}
 {section==='Data'&&<div><h3>Notebook backup</h3><p className="notebookIntro">Export memories and journals. API keys and connection settings are excluded.</p><div className="notebookTools"><button onClick={()=>download(readNotebook())}>Export backup</button><label className="importButton">Import backup<input type="file" accept=".json" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{if(f.size>10000000)throw Error('Backup is too large.');const incoming=validate(JSON.parse(await f.text()));const old=readNotebook();const merged=new Map(old.entries.map(x=>[x.id,x]));incoming.entries.forEach(x=>{if(!merged.has(x.id))merged.set(x.id,x)});saveNotebook({version:1,entries:[...merged.values()]});setStatus('Backup imported. Existing entries were preserved.')}catch(err){setStatus(String(err))}}}/></label></div><h3>Add a note</h3><button onClick={()=>{const book=readNotebook();saveNotebook({...book,entries:[{id:crypto.randomUUID(),kind:'memory',title:'Personal note',text:'',at:new Date().toISOString()},...book.entries]});setStatus('Note added. Open Memories and choose Edit entry to write it.')}}>Add memory note</button></div>}
 {status&&<p role="status">{status}</p>}<footer><button onClick={()=>onSave({...draft,userName:draft.userName.trim(),loaName:draft.loaName.trim()||'Loa',memoryMode:'auto_basic'})}>Save changes</button></footer></section></div>;
}
